// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

class FolderColor {
  final String folder;
  final String color;

  const FolderColor({required this.folder, required this.color});

  @override
  int get hashCode => folder.hashCode ^ color.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderColor &&
          runtimeType == other.runtimeType &&
          folder == other.folder &&
          color == other.color;
}

class Reminder {
  final PlatformInt64? id;
  final String context;
  final String folder;
  final int importance;
  final PlatformInt64 dateOfCreation;
  final String? attachmentPath;
  final bool isPinned;

  const Reminder({
    this.id,
    required this.context,
    required this.folder,
    required this.importance,
    required this.dateOfCreation,
    this.attachmentPath,
    required this.isPinned,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      context.hashCode ^
      folder.hashCode ^
      importance.hashCode ^
      dateOfCreation.hashCode ^
      attachmentPath.hashCode ^
      isPinned.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Reminder &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          context == other.context &&
          folder == other.folder &&
          importance == other.importance &&
          dateOfCreation == other.dateOfCreation &&
          attachmentPath == other.attachmentPath &&
          isPinned == other.isPinned;
}
