// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'schema.dart';

// These functions are ignored because they are not marked as `pub`: `fetch_all_reminders`, `notify_stream`

void initDb({required String path}) =>
    RustLib.instance.api.crateApiSimpleInitDb(path: path);

Stream<List<Reminder>> getReminderStream() =>
    RustLib.instance.api.crateApiSimpleGetReminderStream();

List<FolderColor> getFolderColors() =>
    RustLib.instance.api.crateApiSimpleGetFolderColors();

void updateFolderColor({required String folder, required String color}) =>
    RustLib.instance.api.crateApiSimpleUpdateFolderColor(
      folder: folder,
      color: color,
    );

void addReminder({
  required String context,
  required int importance,
  String? attachmentPath,
}) => RustLib.instance.api.crateApiSimpleAddReminder(
  context: context,
  importance: importance,
  attachmentPath: attachmentPath,
);

void deleteReminder({required PlatformInt64 id}) =>
    RustLib.instance.api.crateApiSimpleDeleteReminder(id: id);

void pinReminder({required PlatformInt64 id, required bool pinned}) =>
    RustLib.instance.api.crateApiSimplePinReminder(id: id, pinned: pinned);

void updateReminderContext({
  required PlatformInt64 id,
  required String context,
}) => RustLib.instance.api.crateApiSimpleUpdateReminderContext(
  id: id,
  context: context,
);

String auditProject({required String projectText}) =>
    RustLib.instance.api.crateApiSimpleAuditProject(projectText: projectText);
